"""ai_decisions (M9 live AI activity)

Revision ID: 70a97e16f0f4
Revises: 842452e9d525
Create Date: 2026-07-12 01:15:07.661798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70a97e16f0f4'
down_revision: Union[str, Sequence[str], None] = '842452e9d525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mint', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('primary_source', sa.String(length=48), nullable=False),
    sa.Column('route', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('outcome_detail', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_mint'), 'ai_decisions', ['mint'], unique=False)
    op.create_index(op.f('ix_ai_decisions_ts'), 'ai_decisions', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_decisions_ts'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_mint'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    # ### end Alembic commands ###
