"""init: positions, closed_trades, risk_state, decision_log_kv

Revision ID: 842452e9d525
Revises: 
Create Date: 2026-07-05 09:57:23.476083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '842452e9d525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mint', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('size_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('tokens_atomic', sa.BigInteger(), nullable=False),
    sa.Column('exit_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('pnl_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_mode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_trades_closed_at'), 'closed_trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_closed_trades_mint'), 'closed_trades', ['mint'], unique=False)
    op.create_table('decision_log_kv',
    sa.Column('ns', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ns', 'key')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mint', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('size_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('tokens_atomic', sa.BigInteger(), nullable=False),
    sa.Column('take_profit_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_hold_s', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_mint'), 'positions', ['mint'], unique=True)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_table('risk_state',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('realized_pnl_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_state')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_mint'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('decision_log_kv')
    op.drop_index(op.f('ix_closed_trades_mint'), table_name='closed_trades')
    op.drop_index(op.f('ix_closed_trades_closed_at'), table_name='closed_trades')
    op.drop_table('closed_trades')
    # ### end Alembic commands ###
